"""Observability: event log, metrics and the latency rig."""

from garagem.obs.curation import Mark, marks, per_author
from garagem.obs.events import (
    DENOMINATOR,
    KINDS,
    Event,
    EventLog,
    MalformedEventError,
    append_events,
    load_events,
    rate_of,
)
from garagem.obs.latency import (
    BUCKETS,
    REQUIRED_BUCKETS,
    SECTION_DEADLINE_S,
    Aggregate,
    Sample,
    append_sample,
    bucket_of,
    load_samples,
    percentile,
    render_report,
    summarise,
)
from garagem.obs.performance import (
    SETLIST_SESSION_S,
    Check,
    model_share,
    performance_checks,
    render_checks,
    runs,
    setlist_checks,
    setlist_session_checks,
)
from garagem.obs.sections import (
    APPROVAL_TARGET,
    CONFORMANCE_TARGET,
    LATENCY_TARGET,
    Report,
    Shot,
    append_shot,
    load_shots,
)

__all__ = [
    "APPROVAL_TARGET",
    "BUCKETS",
    "CONFORMANCE_TARGET",
    "DENOMINATOR",
    "KINDS",
    "LATENCY_TARGET",
    "REQUIRED_BUCKETS",
    "SECTION_DEADLINE_S",
    "SETLIST_SESSION_S",
    "Aggregate",
    "Check",
    "Event",
    "EventLog",
    "MalformedEventError",
    "Mark",
    "Report",
    "Sample",
    "Shot",
    "append_events",
    "append_sample",
    "append_shot",
    "bucket_of",
    "load_events",
    "load_samples",
    "load_shots",
    "marks",
    "model_share",
    "per_author",
    "percentile",
    "performance_checks",
    "rate_of",
    "render_checks",
    "render_report",
    "runs",
    "setlist_checks",
    "setlist_session_checks",
    "summarise",
]
